/**
  ******************************************************************************
  * @file    au5612.c
  * @brief   AU5612 Clock Chip Driver Implementation
  * @author  huangcheng
  * @version 1.0.0
  * @date    2026-01-01
  ******************************************************************************
  */

#include "au5612.h"
#include "hal_i2c.h"
extern I2C_HandleTypeDef hi2c1;

/* AU5612 I2C address (7-bit) verified previously */
#define AU5612_ADDR_7BIT 0x69

typedef enum {
  AU_OP_WRITE8 = 0,
  AU_OP_DELAY_US,
  AU_OP_DELAY_MS,
} au_op_type_t;

typedef struct {
  au_op_type_t type;
  uint16_t a;
  uint8_t  b;
} au_op_t;

static void au_delay_us(uint32_t us)
{
  /* STM32F0: simple busy-wait, good enough for small waits in config scripts */
  volatile uint32_t cycles = (SystemCoreClock / 1000000U) * us / 5U;
  while (cycles--) {
    __NOP();
  }
}

static HAL_StatusTypeDef au_apply_ops(const au_op_t *ops, uint32_t count)
{
  for (uint32_t i = 0; i < count; i++) {
    switch (ops[i].type) {
      case AU_OP_WRITE8: {
        HAL_StatusTypeDef r = hal_i2c_reg_write8(AU5612_ADDR_7BIT, (uint8_t)ops[i].a, ops[i].b, 200);
        if (r != HAL_OK) {
          printf("AU5612 write fail reg=0x%02X val=0x%02X ret=%d\r\n", (unsigned)ops[i].a, ops[i].b, (int)r);
          return r;
        }
      } break;
      case AU_OP_DELAY_US:
        au_delay_us((uint32_t)ops[i].a);
        break;
      case AU_OP_DELAY_MS:
        HAL_Delay((uint32_t)ops[i].a);
        break;
      default:
        break;
    }
  }
  return HAL_OK;
}

/* ---------- Helpers for GPIO general purpose output registers (PAGE0_Mainsys) ---------- */
typedef struct {
  uint8_t reg;
  uint8_t bit; /* 0..7 */
} au_gpio_bit_t;

/**
 * @brief Map GPIO index -> (register, bit) for GPIO general purpose OUTPUT.
 * @note  From AU5612 RegMap:
 * - GPIO0/3 output: GPIO_GEN_PURP_OUTPUT (0xDD) bit0/bit6
 * - GPIO1/2 output: GPIO_GEN_PURP_OUTPUT_6TO15 (0xDB) bit5/bit1
 * - GPIO5..9 output: GPIO_GEN_PURP_OUTPUT_16TO21 (0xD9) bit4/bit0..bit3
 *
 * GPIO4 is not present in these gen-purpose output registers in Rev0.1 regmap.
 */
static uint8_t au_gpio_gen_purp_out_map(uint8_t gpio_index, au_gpio_bit_t *out)
{
  if (out == 0) {
    return 0;
  }
  switch (gpio_index) {
    case 0: out->reg = 0xDD; out->bit = 0; return 1;
    case 3: out->reg = 0xDD; out->bit = 6; return 1;
    case 1: out->reg = 0xDB; out->bit = 5; return 1;
    case 2: out->reg = 0xDB; out->bit = 1; return 1;
    case 5: out->reg = 0xD9; out->bit = 4; return 1;
    case 6: out->reg = 0xD9; out->bit = 0; return 1;
    case 7: out->reg = 0xD9; out->bit = 1; return 1;
    case 8: out->reg = 0xD9; out->bit = 2; return 1;
    case 9: out->reg = 0xD9; out->bit = 3; return 1;
    default: break;
  }
  return 0;
}

static HAL_StatusTypeDef au_select_page(uint8_t page)
{
  /* Common paging style used in your generated script: reg 0xFF selects page. */
  return hal_i2c_reg_write8(AU5612_ADDR_7BIT, 0xFF, page, 200);
}

uint8_t au5612_clkmon_is_locked(void)
{
  uint8_t v = 0;
  if (au_select_page(0x06) != HAL_OK) { /* CLKMON page */
    return 0xFF;
  }
  if (hal_i2c_reg_read8(AU5612_ADDR_7BIT, 0x06, &v, 200) != HAL_OK) { /* STATUS_1_CLKMON */
    return 0xFF;
  }
  /* bit0: 0 = locked, 1 = not locked */
  return ((v & 0x01u) == 0u) ? 1u : 0u;
}

void au5612_apply_generated_config(void)
{
  /* Converted from the provided python script (Generated by angela.yang) */
  static const au_op_t ops[] = {
    /* Step1: HARD Reset */
    { AU_OP_DELAY_MS, 1, 0 },

    /* Configure IO Supply Level */
    { AU_OP_WRITE8, 0xff, 0x00 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x3a, 0x40 },
    { AU_OP_WRITE8, 0x0f, 0x10 },
    { AU_OP_DELAY_US, 1, 0 },
    { AU_OP_WRITE8, 0x57, 0x01 },
    { AU_OP_WRITE8, 0xff, 0x00 },

    /* GENERIC : begin */
    { AU_OP_WRITE8, 0xff, 0x00 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0xec, 0x1c },
    { AU_OP_WRITE8, 0x10, 0x0a },
    { AU_OP_WRITE8, 0x11, 0x08 },
    { AU_OP_WRITE8, 0x12, 0x00 },
    { AU_OP_WRITE8, 0x13, 0x00 },
    { AU_OP_WRITE8, 0x14, 0x00 },
    { AU_OP_WRITE8, 0x15, 0x00 },
    { AU_OP_WRITE8, 0x16, 0x00 },
    { AU_OP_WRITE8, 0x17, 0xa1 },
    { AU_OP_WRITE8, 0x18, 0x40 },
    { AU_OP_WRITE8, 0x1a, 0x0f },
    { AU_OP_WRITE8, 0x1b, 0x0f },
    { AU_OP_WRITE8, 0x1c, 0x8f },
    { AU_OP_WRITE8, 0x1d, 0xcf },
    { AU_OP_WRITE8, 0x1e, 0xfb },
    { AU_OP_WRITE8, 0x1f, 0xcf },
    { AU_OP_WRITE8, 0x20, 0xfb },
    { AU_OP_WRITE8, 0x21, 0xbc },
    { AU_OP_WRITE8, 0x22, 0xcf },
    { AU_OP_WRITE8, 0x23, 0x03 },
    { AU_OP_WRITE8, 0x25, 0x08 },
    { AU_OP_WRITE8, 0x27, 0x40 },
    { AU_OP_WRITE8, 0x28, 0x40 },
    { AU_OP_WRITE8, 0x29, 0x0d },
    { AU_OP_WRITE8, 0x2a, 0xfd },
    { AU_OP_WRITE8, 0x2c, 0xa2 },
    { AU_OP_WRITE8, 0x2d, 0x27 },
    { AU_OP_WRITE8, 0x2f, 0x00 },
    { AU_OP_WRITE8, 0x34, 0x6c },
    { AU_OP_WRITE8, 0x35, 0xff },
    { AU_OP_WRITE8, 0x38, 0x80 },
    { AU_OP_WRITE8, 0x3a, 0x40 },
    { AU_OP_WRITE8, 0x3c, 0xa0 },
    { AU_OP_WRITE8, 0x3f, 0x0e },
    { AU_OP_WRITE8, 0x40, 0x01 },
    { AU_OP_WRITE8, 0xff, 0x00 },
    { AU_OP_WRITE8, 0xff, 0x01 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x10, 0x00 },
    { AU_OP_WRITE8, 0x11, 0x00 },
    { AU_OP_WRITE8, 0x12, 0xa8 },
    { AU_OP_WRITE8, 0x13, 0x00 },
    { AU_OP_WRITE8, 0x14, 0x03 },
    { AU_OP_WRITE8, 0x2e, 0x06 },
    { AU_OP_WRITE8, 0x2f, 0x11 },
    { AU_OP_WRITE8, 0x32, 0x87 },
    { AU_OP_WRITE8, 0x33, 0x88 },
    { AU_OP_WRITE8, 0x34, 0x89 },
    { AU_OP_WRITE8, 0x35, 0x8a },
    { AU_OP_WRITE8, 0x36, 0x09 },
    { AU_OP_WRITE8, 0x37, 0x1a },
    { AU_OP_WRITE8, 0x38, 0xf0 },
    { AU_OP_WRITE8, 0x3c, 0xf0 },
    { AU_OP_WRITE8, 0x42, 0x0a },
    { AU_OP_WRITE8, 0xff, 0x01 },

    /* Update NVM Bank */
    { AU_OP_WRITE8, 0xff, 0x00 },
    { AU_OP_WRITE8, 0x0f, 0x10 },
    { AU_OP_DELAY_US, 10, 0 },

    /* force wakeup the slaves */
    { AU_OP_WRITE8, 0xe1, 0x0f },
    { AU_OP_WRITE8, 0xe0, 0x0f },
    { AU_OP_DELAY_US, 10, 0 },

    /* Proceed to Loop Lock */
    { AU_OP_WRITE8, 0x0f, 0x40 },
    { AU_OP_WRITE8, 0xff, 0x00 },
    /* GENERIC : end */

    /* INPUT_SYS : begin */
    { AU_OP_WRITE8, 0xff, 0x02 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x10, 0x0c },
    { AU_OP_WRITE8, 0x16, 0xff },
    { AU_OP_WRITE8, 0x17, 0xff },
    { AU_OP_WRITE8, 0x18, 0xff },
    { AU_OP_WRITE8, 0x19, 0xff },
    { AU_OP_WRITE8, 0x1a, 0x28 },
    { AU_OP_WRITE8, 0x1b, 0x20 },
    { AU_OP_WRITE8, 0x3f, 0x0a },
    { AU_OP_WRITE8, 0x4f, 0x01 },
    /* Update NVM Bank */
    { AU_OP_WRITE8, 0x0f, 0x10 },
    { AU_OP_DELAY_US, 10, 0 },
    /* Proceed to Loop Lock */
    { AU_OP_WRITE8, 0x0f, 0x40 },
    { AU_OP_DELAY_MS, 5, 0 },
    { AU_OP_WRITE8, 0xff, 0x02 },
    /* INPUT_SYS : end */

    /* CLOCK_MON : begin */
    { AU_OP_WRITE8, 0xff, 0x06 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x10, 0x43 },
    { AU_OP_WRITE8, 0x11, 0x32 },
    { AU_OP_WRITE8, 0x12, 0x28 },
    { AU_OP_WRITE8, 0x14, 0x50 },
    { AU_OP_WRITE8, 0x15, 0xce },
    { AU_OP_WRITE8, 0x16, 0xde },
    { AU_OP_WRITE8, 0x17, 0x05 },
    { AU_OP_WRITE8, 0x1a, 0x2a },
    { AU_OP_WRITE8, 0x1b, 0x08 },
    { AU_OP_WRITE8, 0x1d, 0x19 },
    { AU_OP_WRITE8, 0x1f, 0x11 },
    { AU_OP_WRITE8, 0x27, 0xc0 },
    { AU_OP_WRITE8, 0x37, 0xc0 },
    { AU_OP_WRITE8, 0x47, 0xc0 },
    { AU_OP_WRITE8, 0x70, 0x09 },
    { AU_OP_WRITE8, 0x71, 0xc0 },
    { AU_OP_WRITE8, 0x7c, 0x60 },
    { AU_OP_WRITE8, 0x8b, 0x10 },
    { AU_OP_WRITE8, 0x8f, 0x81 },
    { AU_OP_WRITE8, 0xa7, 0xc0 },
    { AU_OP_WRITE8, 0xc7, 0xc0 },
    { AU_OP_WRITE8, 0xd7, 0xc0 },
    { AU_OP_WRITE8, 0xe7, 0xc0 },
    { AU_OP_WRITE8, 0xff, 0x06 },
    { AU_OP_WRITE8, 0xff, 0x07 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x27, 0x33 },
    { AU_OP_WRITE8, 0x28, 0x07 },
    { AU_OP_WRITE8, 0x29, 0x15 },
    { AU_OP_WRITE8, 0x2a, 0xd5 },
    { AU_OP_WRITE8, 0x2b, 0x55 },
    { AU_OP_WRITE8, 0x2c, 0x55 },
    { AU_OP_WRITE8, 0x2d, 0x55 },
    { AU_OP_WRITE8, 0x2e, 0x18 },
    { AU_OP_WRITE8, 0x2f, 0x01 },
    { AU_OP_WRITE8, 0xff, 0x07 },
    /* Update NVM Bank */
    { AU_OP_WRITE8, 0xff, 0x06 },
    { AU_OP_WRITE8, 0x0f, 0x10 },
    { AU_OP_DELAY_US, 10, 0 },
    /* Proceed to Loop Lock */
    { AU_OP_WRITE8, 0x0f, 0x40 },
    { AU_OP_WRITE8, 0xff, 0x06 },
    /* CLOCK_MON : end */

    /* OUTSYS : begin */
    { AU_OP_WRITE8, 0xff, 0x03 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x2f, 0x03 },
    { AU_OP_WRITE8, 0x44, 0x22 },
    { AU_OP_WRITE8, 0x45, 0x40 },
    { AU_OP_WRITE8, 0x49, 0x02 },
    { AU_OP_WRITE8, 0x4a, 0x0f },
    { AU_OP_WRITE8, 0x4c, 0x20 },
    { AU_OP_WRITE8, 0x4e, 0x40 },
    { AU_OP_WRITE8, 0x4f, 0x03 },
    { AU_OP_WRITE8, 0xff, 0x03 },
    { AU_OP_WRITE8, 0xff, 0x04 },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x2f, 0x63 },
    { AU_OP_WRITE8, 0xff, 0x04 },
    /* Update NVM Bank */
    { AU_OP_WRITE8, 0xff, 0x03 },
    { AU_OP_WRITE8, 0x0f, 0x10 },
    { AU_OP_DELAY_US, 10, 0 },
    /* Proceed to Loop Lock */
    { AU_OP_WRITE8, 0x0f, 0x40 },
    { AU_OP_WRITE8, 0xff, 0x03 },
    /* OUTSYS : end */

    /* PLLA : begin */
    { AU_OP_WRITE8, 0xff, 0x0a },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x10, 0x92 },
    { AU_OP_WRITE8, 0x11, 0x4f },
    { AU_OP_WRITE8, 0x12, 0xf1 },
    { AU_OP_WRITE8, 0x13, 0xad },
    { AU_OP_WRITE8, 0x14, 0x1c },
    { AU_OP_WRITE8, 0x15, 0xa8 },
    { AU_OP_WRITE8, 0x16, 0xff },
    { AU_OP_WRITE8, 0x17, 0x02 },
    { AU_OP_WRITE8, 0x18, 0x0f },
    { AU_OP_WRITE8, 0x19, 0x54 },
    { AU_OP_WRITE8, 0x1b, 0x05 },
    { AU_OP_WRITE8, 0x1c, 0x04 },
    { AU_OP_WRITE8, 0x1d, 0x24 },
    { AU_OP_WRITE8, 0x1f, 0xa0 },
    { AU_OP_WRITE8, 0x22, 0x32 },
    { AU_OP_WRITE8, 0x23, 0x10 },
    { AU_OP_WRITE8, 0x25, 0xa6 },
    { AU_OP_WRITE8, 0x26, 0x42 },
    { AU_OP_WRITE8, 0x28, 0x08 },
    { AU_OP_WRITE8, 0x29, 0x1d },
    { AU_OP_WRITE8, 0x2a, 0x32 },
    { AU_OP_WRITE8, 0x2b, 0x66 },
    { AU_OP_WRITE8, 0x2c, 0x11 },
    { AU_OP_WRITE8, 0x2d, 0x18 },
    { AU_OP_WRITE8, 0x2e, 0x46 },
    { AU_OP_WRITE8, 0x2f, 0x07 },
    { AU_OP_WRITE8, 0x30, 0x35 },
    { AU_OP_WRITE8, 0x31, 0x40 },
    { AU_OP_WRITE8, 0x32, 0x0d },
    { AU_OP_WRITE8, 0x35, 0x98 },
    { AU_OP_WRITE8, 0x38, 0xdf },
    { AU_OP_WRITE8, 0x39, 0xff },
    { AU_OP_WRITE8, 0x3a, 0xff },
    { AU_OP_WRITE8, 0x3b, 0xff },
    { AU_OP_WRITE8, 0x3c, 0xf8 },
    { AU_OP_WRITE8, 0x3d, 0x15 },
    { AU_OP_WRITE8, 0x3e, 0x98 },
    { AU_OP_WRITE8, 0x3f, 0x01 },
    { AU_OP_WRITE8, 0x42, 0x08 },
    { AU_OP_WRITE8, 0x49, 0xff },
    { AU_OP_WRITE8, 0x4a, 0xff },
    { AU_OP_WRITE8, 0x4b, 0xff },
    { AU_OP_WRITE8, 0x4c, 0xff },
    { AU_OP_WRITE8, 0x4d, 0xc0 },
    { AU_OP_WRITE8, 0x4e, 0x20 },
    { AU_OP_WRITE8, 0x4f, 0xdf },
    { AU_OP_WRITE8, 0x57, 0x40 },
    { AU_OP_WRITE8, 0x7f, 0x40 },
    { AU_OP_WRITE8, 0xff, 0x0a },
    { AU_OP_WRITE8, 0xff, 0x1a },
    { AU_OP_WRITE8, 0xbd, 0xc3 },
    { AU_OP_WRITE8, 0x2d, 0x02 },
    { AU_OP_WRITE8, 0x50, 0x08 },
    { AU_OP_WRITE8, 0x5c, 0x0f },
    { AU_OP_WRITE8, 0x5d, 0xff },
    { AU_OP_WRITE8, 0x6c, 0xdd },
    { AU_OP_WRITE8, 0xff, 0x1a },
    /* Update NVM Bank */
    { AU_OP_WRITE8, 0xff, 0x0a },
    { AU_OP_WRITE8, 0x0f, 0x10 },
    { AU_OP_DELAY_US, 10, 0 },
    /* Proceed to Loop Lock */
    { AU_OP_WRITE8, 0x0f, 0x40 },
    { AU_OP_WRITE8, 0xff, 0x0a },
    /* PLLA : end */

    /* final sleep ~32ms */
    { AU_OP_DELAY_MS, 33, 0 },
  };

  (void)au_apply_ops(ops, (uint32_t)(sizeof(ops) / sizeof(ops[0])));
}

void au5612_init(void) 
{
  hal_i2c_bind(&hi2c1);

  au5612_apply_generated_config();
}

